# Generated by Django 5.0.6 on 2024-08-06 01:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_alter_blogpage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmain',
            old_name='about',
            new_name='about_desc',
        ),
    ]
