# Generated by Django 5.0.6 on 2024-08-06 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_rename_about_blogmain_about_desc'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmain',
            name='about_link',
            field=models.ForeignKey(
                blank=True,
                help_text='Select page with additional related content',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.page',
                verbose_name='Optional link',
            ),
        ),
        migrations.AddField(
            model_name='blogmain',
            name='show_tag_cloud',
            field=models.BooleanField(
                default=True,
                help_text='Show tag cloud tile on sidebar?',
                verbose_name='Show tag cloud',
            ),
        ),
    ]
