# Generated by Django 5.0.6 on 2024-07-17 23:30

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='max_recent',
            field=models.IntegerField(
                default=6,
                help_text='Maximum number of recent items to show on home page',
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name='Max recent',
            ),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promoted_page',
            field=models.ForeignKey(
                blank=True,
                help_text='Select content to promote on home page',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.page',
                verbose_name='Promoted content',
            ),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_banner',
            field=models.BooleanField(
                default=False,
                help_text='Show banner on home page?',
                verbose_name='Show banner',
            ),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_contact_info',
            field=models.BooleanField(
                default=False,
                help_text='Show content form and social media links on home page?',
                verbose_name='Show contact info',
            ),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_happening',
            field=models.BooleanField(
                default=False,
                help_text='Show upcoming events, shows, etc. on home page?',
                verbose_name='Show events',
            ),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_promo',
            field=models.BooleanField(
                default=False,
                help_text='Show promoted content on home page?',
                verbose_name='Show promoted',
            ),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_recent',
            field=models.BooleanField(
                default=False,
                help_text='Show recent content on home page?',
                verbose_name='Show recent',
            ),
        ),
        migrations.CreateModel(
            name='HomePageBanner',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'sort_order',
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    'text',
                    models.CharField(
                        blank=True,
                        help_text='Text to display on the slide',
                        max_length=255,
                        verbose_name='Slide text',
                    ),
                ),
                (
                    'image',
                    models.ForeignKey(
                        blank=True,
                        help_text='Image for the slide',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wagtailimages.image',
                        verbose_name='Slide image',
                    ),
                ),
                (
                    'slide01',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='banner_slide01',
                        to='home.homepage',
                    ),
                ),
                (
                    'slide02',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='banner_slide02',
                        to='home.homepage',
                    ),
                ),
                (
                    'slide03',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='banner_slide03',
                        to='home.homepage',
                    ),
                ),
                (
                    'slide04',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='banner_slide04',
                        to='home.homepage',
                    ),
                ),
                (
                    'url',
                    models.ForeignKey(
                        blank=True,
                        help_text='Optional link for the slide',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wagtailcore.page',
                        verbose_name='Slide link',
                    ),
                ),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageEvents',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'sort_order',
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    'event01',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='event_item01',
                        to='home.homepage',
                    ),
                ),
                (
                    'event02',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='event_item02',
                        to='home.homepage',
                    ),
                ),
                (
                    'event_page',
                    models.ForeignKey(
                        blank=True,
                        help_text='Select event content to promote on home page',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wagtailcore.page',
                        verbose_name='Promoted event',
                    ),
                ),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
