# Generated by Django 5.0.6 on 2024-08-01 23:21

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='max_recent',
            field=models.IntegerField(
                default=6,
                help_text='Maximum recent items to show on home page',
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name='Max recent',
            ),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_page',
            field=models.ForeignKey(
                blank=True,
                help_text='Select content to promote on home page',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.page',
                verbose_name='Promoted content',
            ),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_contact_info',
            field=models.BooleanField(
                default=True,
                help_text='Show content form and social media links on home page?',
                verbose_name='Show contact info',
            ),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_happening',
            field=models.BooleanField(
                default=False,
                help_text='Show upcoming events, shows, etc. on home page?',
                verbose_name='Show events',
            ),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_newsletter',
            field=models.BooleanField(
                default=False,
                help_text='Show newsletter sign-up on home page?',
                verbose_name='Show newsletter',
            ),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_promo',
            field=models.BooleanField(
                default=False,
                help_text='Show promoted content on home page?',
                verbose_name='Show promoted',
            ),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_recent',
            field=models.BooleanField(
                default=False,
                help_text='Show recent content on home page?',
                verbose_name='Show recent',
            ),
        ),
        migrations.CreateModel(
            name='BannerSlide',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'sort_order',
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    'caption',
                    models.CharField(
                        blank=True,
                        help_text='Optional text to display on the banner image',
                        max_length=255,
                        verbose_name='Banner text',
                    ),
                ),
                (
                    'credit_text',
                    models.CharField(
                        blank=True,
                        help_text='Image credits display below image.',
                        max_length=255,
                        verbose_name='Image credit',
                    ),
                ),
                (
                    'credit_url',
                    models.URLField(
                        blank=True,
                        help_text='URL for image credits.',
                        verbose_name='Credit URL',
                    ),
                ),
                (
                    'image',
                    models.ForeignKey(
                        blank=True,
                        help_text='Use image ratio 20:9 and max size 2000 x 900 px',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wagtailimages.image',
                        verbose_name='Banner image',
                    ),
                ),
                (
                    'page',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='banner_slides',
                        to='home.homepage',
                    ),
                ),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'sort_order',
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    'event',
                    models.ForeignKey(
                        help_text='Select event item to promote on home page',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='wagtailcore.page',
                        verbose_name='Promoted event',
                    ),
                ),
                (
                    'page',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='event_items',
                        to='home.homepage',
                    ),
                ),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
