# Generated by Django 5.0.6 on 2024-08-06 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0003_homepage_max_recent_homepage_promo_page_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='promo_page',
            new_name='promo_link',
        ),
    ]
