# Generated by Django 5.0.6 on 2024-07-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0003_homepage_max_recent_homepage_promoted_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_newsletter',
            field=models.BooleanField(
                default=False,
                help_text='Show newsletter sign-up on home page?',
                verbose_name='Show newsletter',
            ),
        ),
    ]
