# Generated by Django 5.0.6 on 2024-07-17 23:30

import django.core.validators
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailmarkdown.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('base', '0001_initial'),
        (
            'taggit',
            '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx',
        ),
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTagIndexPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SectionMain',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
                (
                    'show_banner',
                    models.BooleanField(
                        default=False,
                        help_text='Show banner on section landing page?',
                        verbose_name='Show banner',
                    ),
                ),
                (
                    'show_promo',
                    models.BooleanField(
                        default=False,
                        help_text='Show promoted content on section landing page?',
                        verbose_name='Show promoted',
                    ),
                ),
                (
                    'show_happening',
                    models.BooleanField(
                        default=False,
                        help_text='Show upcoming events, shows, etc. on section landing page?',
                        verbose_name='Show events',
                    ),
                ),
                (
                    'show_recent',
                    models.BooleanField(
                        default=False,
                        help_text='Show recent content on section landing page?',
                        verbose_name='Show recent',
                    ),
                ),
                (
                    'max_recent',
                    models.IntegerField(
                        default=6,
                        help_text='Maximum number of recent items to show on section landing page',
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name='Max recent',
                    ),
                ),
                (
                    'show_contact_info',
                    models.BooleanField(
                        default=False,
                        help_text='Show content form and social media links on section landing page?',
                        verbose_name='Show contact info',
                    ),
                ),
                (
                    'promoted_page',
                    models.ForeignKey(
                        blank=True,
                        help_text='Select content to promote on section landing page',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wagtailcore.page',
                        verbose_name='Promoted content',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SectionMainBanner',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'sort_order',
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    'text',
                    models.CharField(
                        blank=True,
                        help_text='Text to display on the slide',
                        max_length=255,
                        verbose_name='Slide text',
                    ),
                ),
                (
                    'image',
                    models.ForeignKey(
                        blank=True,
                        help_text='Image for the slide',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wagtailimages.image',
                        verbose_name='Slide image',
                    ),
                ),
                (
                    'slide01',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='banner_slide01',
                        to='sections.sectionmain',
                    ),
                ),
                (
                    'slide02',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='banner_slide02',
                        to='sections.sectionmain',
                    ),
                ),
                (
                    'slide03',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='banner_slide03',
                        to='sections.sectionmain',
                    ),
                ),
                (
                    'slide04',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='banner_slide04',
                        to='sections.sectionmain',
                    ),
                ),
                (
                    'url',
                    models.ForeignKey(
                        blank=True,
                        help_text='Optional link for the slide',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wagtailcore.page',
                        verbose_name='Slide link',
                    ),
                ),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionMainEvents',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'sort_order',
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    'event01',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='event_item01',
                        to='sections.sectionmain',
                    ),
                ),
                (
                    'event02',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='event_item02',
                        to='sections.sectionmain',
                    ),
                ),
                (
                    'event_page',
                    models.ForeignKey(
                        blank=True,
                        help_text='Select event content to promote on home page',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wagtailcore.page',
                        verbose_name='Promoted event',
                    ),
                ),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionPage',
            fields=[
                (
                    'page_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wagtailcore.page',
                    ),
                ),
                ('date', models.DateField(verbose_name='Post date')),
                ('intro', models.CharField(max_length=250)),
                (
                    'body',
                    wagtail.fields.StreamField(
                        [
                            (
                                'heading_block',
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            'heading_text',
                                            wagtail.blocks.CharBlock(
                                                form_classname='title', required=True
                                            ),
                                        ),
                                        (
                                            'size',
                                            wagtail.blocks.ChoiceBlock(
                                                blank=True,
                                                choices=[
                                                    ('', 'Select heading size'),
                                                    ('h2', 'H2'),
                                                    ('h3', 'H3'),
                                                    ('h4', 'H4'),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                'markdown_block',
                                wagtailmarkdown.blocks.MarkdownBlock(icon='code'),
                            ),
                            (
                                'image_block',
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            'image',
                                            wagtail.images.blocks.ImageChooserBlock(required=True),
                                        ),
                                        (
                                            'caption',
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            'attribution',
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                'embed_block',
                                wagtail.embeds.blocks.EmbedBlock(
                                    help_text='Insert a URL to embed. For example, https://www.youtube.com/watch?v=SGJFWirQ3ks',
                                    icon='media',
                                ),
                            ),
                        ],
                        blank=True,
                        help_text='Create a landing/main page for a section using Markdown.',
                    ),
                ),
                (
                    'authors',
                    modelcluster.fields.ParentalManyToManyField(blank=True, to='base.author'),
                ),
                (
                    'feed_image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='wagtailimages.image',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SectionPageGalleryImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'sort_order',
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('credit_text', models.CharField(blank=True, max_length=250)),
                ('credit_url', models.URLField(blank=True)),
                (
                    'image',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='wagtailimages.image',
                    ),
                ),
                (
                    'page',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='gallery_images',
                        to='sections.sectionpage',
                    ),
                ),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionPageRelatedLink',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'sort_order',
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ('name', models.CharField(max_length=250)),
                ('url', models.URLField()),
                (
                    'page',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='related_links',
                        to='sections.sectionpage',
                    ),
                ),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionPageTag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'page',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tagged_items',
                        to='sections.sectionpage',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_items',
                        to='taggit.tag',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='sections.SectionPageTag',
                to='taggit.Tag',
                verbose_name='Tags',
            ),
        ),
    ]
