# Generated by Django 5.0.6 on 2024-08-05 21:09

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'heading_block',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'heading_text',
                                    wagtail.blocks.CharBlock(
                                        form_classname='title', required=True
                                    ),
                                ),
                                (
                                    'size',
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ('', 'Select heading size'),
                                            ('h2', 'H2'),
                                            ('h3', 'H3'),
                                            ('h4', 'H4'),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        'paragraph_block',
                        wagtail.blocks.RichTextBlock(
                            icon='pilcrow', template='base/blocks/paragraph_block.html'
                        ),
                    ),
                    (
                        'image_block',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'image',
                                    wagtail.images.blocks.ImageChooserBlock(required=True),
                                ),
                                ('caption', wagtail.blocks.CharBlock(required=False)),
                                (
                                    'credit_text',
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                ('credit_url', wagtail.blocks.URLBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'embed_block',
                        wagtail.embeds.blocks.EmbedBlock(
                            help_text='Insert a URL to embed. For example, https://www.youtube.com/watch?v=SGJFWirQ3ks',
                            icon='media',
                            template='base/blocks/embed_block.html',
                        ),
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'heading_block',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'heading_text',
                                    wagtail.blocks.CharBlock(
                                        form_classname='title', required=True
                                    ),
                                ),
                                (
                                    'size',
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ('', 'Select heading size'),
                                            ('h2', 'H2'),
                                            ('h3', 'H3'),
                                            ('h4', 'H4'),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        'paragraph_block',
                        wagtail.blocks.RichTextBlock(
                            icon='pilcrow', template='base/blocks/paragraph_block.html'
                        ),
                    ),
                    (
                        'image_block',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'image',
                                    wagtail.images.blocks.ImageChooserBlock(required=True),
                                ),
                                ('caption', wagtail.blocks.CharBlock(required=False)),
                                (
                                    'credit_text',
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                ('credit_url', wagtail.blocks.URLBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'embed_block',
                        wagtail.embeds.blocks.EmbedBlock(
                            help_text='Insert a URL to embed. For example, https://www.youtube.com/watch?v=SGJFWirQ3ks',
                            icon='media',
                            template='base/blocks/embed_block.html',
                        ),
                    ),
                ],
                blank=True,
                verbose_name='Page body',
            ),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'heading_block',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'heading_text',
                                    wagtail.blocks.CharBlock(
                                        form_classname='title', required=True
                                    ),
                                ),
                                (
                                    'size',
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ('', 'Select heading size'),
                                            ('h2', 'H2'),
                                            ('h3', 'H3'),
                                            ('h4', 'H4'),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        'paragraph_block',
                        wagtail.blocks.RichTextBlock(
                            icon='pilcrow', template='base/blocks/paragraph_block.html'
                        ),
                    ),
                    (
                        'image_block',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'image',
                                    wagtail.images.blocks.ImageChooserBlock(required=True),
                                ),
                                ('caption', wagtail.blocks.CharBlock(required=False)),
                                (
                                    'credit_text',
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                ('credit_url', wagtail.blocks.URLBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'embed_block',
                        wagtail.embeds.blocks.EmbedBlock(
                            help_text='Insert a URL to embed. For example, https://www.youtube.com/watch?v=SGJFWirQ3ks',
                            icon='media',
                            template='base/blocks/embed_block.html',
                        ),
                    ),
                ],
                blank=True,
                help_text='Create a plain page without sidebar using RichText format.',
                verbose_name='Page body',
            ),
        ),
    ]
