# Generated by Django 5.0.6 on 2024-08-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.TextField(default='Carolina Model Railroaders, Inc.', help_text='Copyright text to display in the footer.'),
        ),
        migrations.DeleteModel(
            name='CopyrightText',
        ),
    ]
