# Generated by Django 5.0.6 on 2024-07-18 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsettings',
            old_name='visit_hours_FRI',
            new_name='open_FRI',
        ),
        migrations.RenameField(
            model_name='contactsettings',
            old_name='visit_hours_MON',
            new_name='open_MON',
        ),
        migrations.RenameField(
            model_name='contactsettings',
            old_name='visit_hours_SAT',
            new_name='open_SAT',
        ),
        migrations.RenameField(
            model_name='contactsettings',
            old_name='visit_hours_SUN',
            new_name='open_SUN',
        ),
        migrations.RenameField(
            model_name='contactsettings',
            old_name='visit_hours_THU',
            new_name='open_THU',
        ),
        migrations.RenameField(
            model_name='contactsettings',
            old_name='visit_hours_TUE',
            new_name='open_TUE',
        ),
        migrations.RenameField(
            model_name='contactsettings',
            old_name='visit_hours_WED',
            new_name='open_WED',
        ),
        migrations.RenameField(
            model_name='contactsettings',
            old_name='visit_hours_holidays',
            new_name='open_holidays',
        ),
    ]
