# Generated by Django 5.0.6 on 2024-08-06 01:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0002_alter_formpage_body_alter_gallerypage_body_and_more'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tag_cloud_desc',
            field=wagtail.fields.RichTextField(
                blank=True, help_text='Text to describe the tag cloud tile'
            ),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tag_cloud_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tag_cloude_image',
            field=models.ForeignKey(
                blank=True,
                help_text='Landscape mode only; horizontal width between 1000px and 3000px.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailimages.image',
            ),
        ),
    ]
