# Generated by Django 5.0.6 on 2024-08-06 01:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0003_sitesettings_tag_cloud_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='tag_cloude_image',
            new_name='tag_cloud_image',
        ),
    ]
