# Generated by Django 5.0.6 on 2024-08-07 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0004_rename_tag_cloude_image_sitesettings_tag_cloud_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pagination_max_pages',
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text='Maximum number of pages (7-15) to show in pagination.',
                validators=[
                    django.core.validators.MinValueValidator(7),
                    django.core.validators.MaxValueValidator(15),
                ],
                verbose_name='Max pages in pagination',
            ),
        ),
    ]
